name: Raffle
main: com.drawwdev.raffle.Main
version: 1.3.7
author: drawwdev
website: https://github.com/Draww/Raffle
softdepend: [PlaceholderAPI]
commands:
  raffle:
    description: Raffle main command
    usage: /raffle
permissions:
  raffle.*:
    default: op
    children:
      raffle.help: true
      raffle.start: true
      raffle.stop: true
      raffle.types: true
      raffle.reload: true
  raffle.help:
    default: op
  raffle.start:
    default: op
  raffle.stop:
    default: op
  raffle.types:
    default: op
  raffle.reload:
    default: op