name: Raffle
main: com.drawwdev.raffle.Main
version: 1.3.5.1
author: drawwdev
website: https://github.com/Draww/Raffle
commands:
  raffle:
    description: Raffle main command
    usage: /raffle
permissions:
  raffle.*:
    default: op